### PR TITLE
Add types and stuff 

### PR DESCRIPTION
**Pull request by aslak01**
Hey,

This ended up taking a fair while longer than I had thought, but it ended up being quite instructive and useful for me. 

I ended up making some small refactors to some parts of the code, in order to make the typescript compiler and eslint happy, but nothing major.

Have a look and let me know what you think.

### CODE REVIEW

**Comment by JeffreyPalmer** [comment]
Thanks! I'll take a look at this when I have a minute and see if I have any feedback. 🙏

**Comment by aslak01** [comment]
It ended up being quite a bit more involved than anticipated, and apparently there was some inconsistent prettier rules applied to the last push, so although I tried to make the diffs as similar as possible at the end with regard to tabs, spaces, etc, it wasn't quite successful. Maybe it'd be an idea to merge a pr with the same rules applied as a baseline before trying to look at this?

**Comment by JeffreyPalmer** [comment]
It's funny. When I wrote this code way back when, I didn't really know D3, or JS/TS, or Svelte. Your code feels like how I would write this now, so thanks for that.

From what I can see so far, this looks good. I'll keep reviewing but I don't foresee any issues. 🙏

**Comment by JeffreyPalmer** [comment]
Thanks! 🙏

**Comment by aslak01** [comment]
Not sure if I mentioned it, but I came across this repo looking to learn more about d3, and I definitely picked up a bunch of useful stuff not only about d3 but also typescript doing this so no problem :)

**Comment by aslak01** [comment]
I borrowed some ideas for my weather forecast (and trains) raspberry pi thing :)

miniw

Need to improve the way it relates scales a bit, was thinking to increase the intensity of the dots relative to amount of rain. Axis ticks with scale don't really work well at the distance it's being viewed.

**Comment by JeffreyPalmer** [comment]
This is amazing! I love these types of projects. I've been wanting to do some similar types of things for a little while now. Gonna have to take a look.

Thanks so much for sharing! 🙏

**Comment by aslak01** [comment]
I'm using this https://github.com/samsonmking/epaper.js with a display from waveshare, so the contents is just a svelte website, which epaper.js's builtin refresh cycle pings every 10 mins which keeps the info fresh enough. Works pretty well. Only one bug in epaper.js that's annoying is that if the pi loses power for any reason I have to ssh in and manually restart the process.

**Pull request merged**
