### PR TITLE
Updated to svelte kit

### PR DESCRIPTION
**Pull request by aslak01**
Hey,

I wanted to give this a spin up and have a look, but there were some dependency issues booting up snowpack, and rather than sorting it out, I ported the examples to Svelte Kit which should remain stable for a bit longer, since it just reached 1.0. Have a look if you want.

### CODE REVIEW

**Comment by JeffreyPalmer** [comment]
Wow this is great. I was just doing some work with SvelteKit myself but honestly had forgotten about the state of this repo. Thanks for submitting this PR!

**Comment by aslak01** [comment]
No problem :) My last larger svelte project was in the Snowpack days too, but I'm also getting back into it, and came here looking for some d3 inspiration. 

By the way, as I was doing the conversion I noticed my linter found some more nitpicks around in the code, if you don't mind I could fix those as I poke around and do another PR.

**Comment by JeffreyPalmer** [comment]
That would be great! 🙏

I was pretty new to both d3 and svelte when I wrote this code, so I'm sure things could be smoothed out a little. That said, I also don't really want it to diverge too much from the content in the blog posts without some indication that it has changed, so if you do make changes, it would be super helpful if you could add a comment describing the change for any future readers.

Thanks!

**Comment by aslak01** [comment]
Oh no, I'm not talking about changing the intention of the code, just typescript nitpicks about potential null returns from other functions and stuff like that. I'vet got some mental capacity to spare and combined with your blog posts, I think I can pick up a lot about d3 by doing it. If I want to play around with the output or content, I'll keep it in my fork :)

**Pull request merged**
